/* ===================================================================
   sprites.js — pixel art for Battle mode (data only)
   Grids are authored facing right. Each character indexes the sprite's
   palette; "." is transparent. game.js adds a 1px outline when drawing.
   =================================================================== */
const SPRITES = {
  slime: {
    pal: { a: "#5ee6a8", b: "#2fa87a", W: "#e9fff5", e: "#0b3d2c" },
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "......aaaa......",
      "....aaaaaaaa....",
      "...aaWWaaaaaa...",
      "..aaaWaaaaaaaa..",
      "..aaaaaaaaaaaa..",
      ".aaaaeaaaaeaaaa.",
      ".aaaaeaaaaeaaaa.",
      ".aaaaaaaeeaaaaa.",
      ".baaaaaaaaaaaab.",
      ".bbaaaaaaaaaabb.",
      "..bbbbbbbbbbbb..",
    ],
  },  bat: {
    pal: { a: "#8b5cf6", e: "#fde047", f: "#ffffff", w: "#5b21b6", W: "#a78bfa" },
    rows: [
      "................",
      "................",
      ".....a....a.....",
      ".....aa..aa.....",
      "w....aaaaaa....w",
      "ww...aeaaea...ww",
      "www..aaffaa..www",
      "wwwwwaaaaaawwwww",
      ".wwwwwaaaawwwww.",
      "..wWwWaaaaWwWw..",
      "..W..W.aa.W..W..",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },  ghost: {
    pal: { a: "#e2e8f0", b: "#94a3b8", c: "#1e1b3a", e: "#67e8f9" },
    rows: [
      "................",
      "......aaaa......",
      "....aaaaaaaa....",
      "...aaaaaaaaaa...",
      "..aaacccccccaa..",
      "..aaccecccecaa..",
      "..aaccccccccaa..",
      ".aaaacccccccaaa.",
      ".aaaaaaaaaaaaaa.",
      ".abaaaaaaaaaaba.",
      "..aaaaaaaaaaaa..",
      "..abaaaabaaaba..",
      "..aaaaaaaaaaaa..",
      "..aa.aaa.aaa.a..",
      "..a...a...a.....",
      "................",
    ],
  },  knight: {
    pal: { A: "#8e97a8", a: "#586173", d: "#2d3443", v: "#0b0b12", r: "#f43f5e", p: "#be123c", P: "#881337",
           k: "#5b2177", K: "#33124a", s: "#f1f5f9", S: "#94a3b8", g: "#c9a227", G: "#8a6d12" },
    rows: [
      "......ppP.......",
      ".....AAAAa...s..",
      "....AAaaaad..sS.",
      "....Avvvvvd..sS.",
      "....Avrvrvd..sS.",
      "....aaaaaad..sS.",
      "...kAAaaadda.sS.",
      "..kAAaaaaaddggg.",
      "..kAaaaraaad.a..",
      "..kdAaaaaaddaa..",
      ".kkdgggGgggd....",
      ".kKdaaaaaaad....",
      ".kKdaad.daad....",
      "kkKdAad.dAad....",
      "kK.daad.daad....",
      "...dddd.dddd....",
    ],
  },  hero_knight: {
    pal: { s: "#f6c9a2", S: "#dba07c", e: "#1b1b24", E: "#ffffff", p: "#ef9a8c", m: "#b85a4c", h: "#7a4527", H: "#4f2a17", j: "#a9663a", b: "#6b3e1f", g: "#f2b632", l: "#8a5530", L: "#55301a", w: "#f1f5ff", W: "#a9b6d0", y: "#e3b341", Y: "#a87a1c", A: "#c3cad6", a: "#8b95a7", d: "#5b6577", r: "#e2574c", R: "#a8322a", c: "#3b6fd4", C: "#264a99", t: "#9aa3b5", T: "#5f6878" },
    rows: [
      "........rR...........",
      ".......rrRR.......w..",
      ".....AAAAAAAa.....wW.",
      "....AAAAAAAAAa....wW.",
      "...AAAAAAAAAAAa...wW.",
      "..dAAAAAAAAAAAAa..wW.",
      "..dAaaaaaaaaaaaad.wW.",
      "..dASsssshsssssad.wW.",
      "..dASssEesssEesad.wW.",
      "..dASsseessseesad.wW.",
      "..dASsseessseesad.wW.",
      "..dASsppssmsppsad.wW.",
      "..dASSssssssSS.ad.wW.",
      "...cccccccccccS..YyyY",
      "..CccttttttttccLl.Y..",
      ".CCcttttTttttt.lL....",
      ".CCcbbbbgbbbbb.......",
      "CCcctttttttttT.......",
      "CC..ttTTt.tTTt.......",
      "....lll...lll........",
      "...LLLL..LLLL........",
    ],
  },
  hero_wizard: {
    pal: { s: "#f6c9a2", S: "#dba07c", e: "#1b1b24", E: "#ffffff", p: "#ef9a8c", m: "#b85a4c", h: "#7a4527", H: "#4f2a17", j: "#a9663a", b: "#6b3e1f", g: "#facc15", l: "#8a5530", L: "#55301a", w: "#f1f5ff", W: "#a9b6d0", y: "#facc15", Y: "#a87a1c", V: "#5b21b6", v: "#7c3aed", c: "#6d28d9", C: "#4c1d95", t: "#8b5cf6", T: "#5b21b6", o: "#67e8f9", O: "#ecfeff" },
    rows: [
      ".....Vv..........oOo.",
      "......vV........oOOoo",
      "......vvV........ooo.",
      ".....vvvvV........l..",
      "....vvvvyvV.......l..",
      "...vvvvvvvvV......lL.",
      "...VyyyyyyyyyV....lL.",
      ".VVvvvvvvvvvvvvVV.lL.",
      ".Hhsssshsssssh....lL.",
      ".HhssEesssEess....lL.",
      ".Hhsseesssees.....lL.",
      ".Hhsseesssees.....lL.",
      ".Hhsppssmspps.....lL.",
      ".HhSssssssSS......lL.",
      "...cccccccccccS...lL.",
      "..CccttttttttccLl.lL.",
      ".CCcttttTttttt.lL.lL.",
      ".CCcbbbbgbbbbb....lL.",
      "CCcctttttttttT....lL.",
      "CC..ttTTt.tTTt....lL.",
      "....lll...lll.....lL.",
      "...LLLL..LLLL.....l..",
    ],
  },
  hero_ranger: {
    pal: { s: "#f6c9a2", S: "#dba07c", e: "#1b1b24", E: "#ffffff", p: "#ef9a8c", m: "#b85a4c", h: "#7a4527", H: "#4f2a17", j: "#a9663a", b: "#6b3e1f", g: "#2f8f5b", l: "#8a5530", L: "#55301a", w: "#f1f5ff", W: "#e5e7eb", y: "#e3b341", Y: "#a87a1c", G: "#1f6140", c: "#2f8f5b", C: "#1f6140", t: "#8a5a3b", T: "#5e3b25", q: "#a9663a", Q: "#6b3e1f" },
    rows: [
      ".....................",
      "......gggg...........",
      "....gggggggg.........",
      "...gggggggggg........",
      "..GgggggggggggG..q...",
      "..GgggggggggggG..Wq..",
      "..GgggGshhhshgG..W.q.",
      "..Ggsssshsssssg..W.q.",
      "..GgssEesssEesg..W.qQ",
      "..Ggsseessseesg..W.qQ",
      "..Ggsseessseesg..W.qQ",
      "..Ggsppssmsppsg..W.qQ",
      "..GgSssssssSS.g..W.qQ",
      "...cccccccccccS..W.qQ",
      "..CccttttttttccLlW.qQ",
      ".CCcttttTttttt.lLW.qQ",
      ".CCcbbbbybbbbb...W.q.",
      "CCcctttttttttT...Wq..",
      "CC..ttTTt.tTTt...q...",
      "....lll...lll........",
      "...LLLL..LLLL........",
    ],
  },
  slimeking: {
    pal: { a: "#4ade80", b: "#15803d", W: "#ecfdf5", e: "#052e16", E: "#ef4444", m: "#052e16", f: "#ffffff", g: "#facc15", G: "#b45309", R: "#ef4444" },
    rows: [
      "...g..g..g..g...",
      "...gg.gg.gg.gg..",
      "...gRggGggRggg..",
      "...gggggggggggg.",
      "...aaaaaaaaaaa..",
      "..aaWWaaaaaaaaa.",
      ".aaaWaaaaaaaaaaa",
      ".aaeeeaaaaaeeeaa",
      ".aaaeEaaaaaaeEaa",
      ".aaaeeaaaaaaeeaa",
      "aaaaaaaaaaaaaaaa",
      "aaaaammmmmmmaaaa",
      "aaaaamfmfmfmaaaa",
      "baaaaaaaaaaaaaab",
      "bbaaaaaaaaaaaabb",
      ".bbbbbbbbbbbbbb.",
    ],
  },
  golem: {
    pal: { A: "#9ca3af", a: "#6b7280", d: "#374151", e: "#22d3ee", g: "#4d7c0f", o: "#f97316", O: "#fde047" },
    rows: [
      "....aaaaaaaa....",
      "...aAAAAAAAAa...",
      "...aAeeAAeeAa...",
      "...aAAAAAAAAa...",
      "..daaAAAAAAaad..",
      ".ddAAgAAAAAAAdd.",
      "dAAAAAAAAAgAAAAd",
      "dAAAAAAoOAAAAAAd",
      "dAAd.AAooAAA.dAd",
      "dAAd.AAAAAAA.dAd",
      "dgAd.AAgAAAA.dAd",
      "ddd..AAAAAAA..dd",
      ".....AAd..dAA...",
      "....dAAd..dAAd..",
      "....dddd..dddd..",
      "................",
    ],
  },
  lich: {
    pal: { y: "#facc15", V: "#6d28d9", v: "#3b0764", w: "#e7e5e4", k: "#1c1917", g: "#4ade80", o: "#4ade80", O: "#dcfce7", l: "#78350f" },
    rows: [
      "..y.y.y......o..",
      "..yyyyy.....oOo.",
      ".vVVVVVv.....o..",
      "vVVwwwwwVv...l..",
      "vVwkgwkgwVv..l..",
      "vVwwwwwwwVv..l..",
      "vVwwkkkwwVv..l..",
      ".vVwkwkwVv...l..",
      "vvVVwwwVVvvvwl..",
      "vVVVVVVVVVVwwl..",
      "vVVgVVVVVVv..l..",
      "vVVVVVgVVVv..l..",
      ".vVVVVVVVv...l..",
      "..vVVVVVVv...l..",
      "..vvVvVvVv......",
      "...v.v.v.v......",
    ],
  },
  dragon: {
    pal: { a: "#a11313", A: "#d42a2a", d: "#4a0606", B: "#1a0202", H: "#e7dcc0", W: "#1e0303", w: "#6b1010", E: "#fde047", k: "#1a0202", m: "#140202", F: "#ffffff", g: "#f59e0b", G: "#b45309", c: "#e7dcc0" },
    rows: [
      "W.......HH..........HH.......W",
      "WW.......HH........HH.......WW",
      "WwW.......HH......HH.......WwW",
      "WwwW.......HddddddH.......WwwW",
      "WwwwW.....daaAaaAaad.....WwwwW",
      "WwWwwW....daBaAAaBad....WwwWwW",
      "WwWwwwW...daaBBBBaad...WwwwWwW",
      "WwwWwwwW..daEEaaEEad..WwwwWwwW",
      "WwwWwWwwW.daaEaaEaad.WwwWwWwwW",
      "WWwwWwWwWWdaaakkaaadWWwWwWwwWW",
      ".WwW.WwWwWdamFmmFmadWwWwW.WwW.",
      "..W..WW.WWddmmmmmmddWW.WW..W..",
      ".......WWddmFmmmmFmddWW.......",
      "........dddaaaggaaaddd........",
      ".......cdaAaaggggaaAadc.......",
      "......cdaaAaagGGgaaAaadc......",
      ".......ddaaaaggggaaaadd.......",
      ".......daa.daGggGad.aad.......",
      "......dda..daaaaaad..add......",
      ".....ccdc..ccdccdcc..cdcc.....",
    ],
  },
};

/* Palette swaps: same drawing, new colors. */
(function () {
  const swap = (base, name, pal) => { SPRITES[name] = { rows: SPRITES[base].rows, pal: Object.assign({}, SPRITES[base].pal, pal) }; };
  swap("slime", "slime_ice",   { a: "#7dd3fc", b: "#0284c7", e: "#082f49" });
  swap("slime", "slime_magma", { a: "#fb923c", b: "#c2410c", W: "#fef3c7", e: "#431407" });
  swap("bat",   "bat_blood",   { a: "#dc2626", w: "#450a0a", W: "#991b1b", e: "#fde047" });
  swap("ghost", "ghost_violet",{ a: "#c4b5fd", b: "#7c3aed", c: "#1e1b4b", e: "#f0abfc" });
  swap("knight","commander",   { A: "#4b4b63", a: "#2e2e40", d: "#17171f", r: "#facc15", p: "#a21caf", P: "#701a75",
                                 k: "#7f1d1d", K: "#450a0a", g: "#facc15", G: "#a16207", s: "#fecaca", S: "#f87171" });
})();
